# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes to the fafali-page branch
  push:
    branches:
      - fafali-page

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Deploy job
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./team-pages  # Path to your HTML files
          user_name: GitHub Actions
          user_email: actions@github.com
          commit_message: 'Deployed from GitHub Actions'

